version: 1
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env:
      DATABASE_URL: mysql://dbuser:dbpassword@mysql:3306/dbname
    ports:
      - 8080:80
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - 3306:3306
